version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:5050"
    depends_on:
      - db_user
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_user:5432/ql_user
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Cntt@2022
    networks:
      - mynetwork

  db_user:
    image: postgres:13
    container_name: db_user
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Cntt@2022
      - POSTGRES_DB=ql_user
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork: